# Generated by Django 4.1.2 on 2022-10-25 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('mobile', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('passport', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Events.client')),
                ('company', models.CharField(max_length=35)),
            ],
        ),
    ]
